#文件路径
data /home/pigsy/search_engine/data
include /home/pigsy/search_engine/include
yuliao /home/pigsy/search_engine/yuliao
art /home/pigsy/search_engine/yuliao/art
english /home/pigsy/search_engine/yuliao/english

#通信配置
ip 192.168.195.131
port 8888